name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Install dependencies
      run: dotnet restore Diwen.Aifmd.Test/Diwen.Aifmd.Test.csproj
    - name: Build
      run: dotnet build --configuration Release --no-restore Diwen.Aifmd.Test/Diwen.Aifmd.Test.csproj
    - name: Test
      run: dotnet test --no-restore --verbosity normal Diwen.Aifmd.Test/Diwen.Aifmd.Test.csproj
